### ISSUE TITLE
Run baseline method NovelD, error happened。

### ISSUE THREAD

**Issue by dooliu** [swan-utokyo/deir#5]
When I tried to run the NovelD algorithm to compare the two methods, an error occurred!

the command order like this:

PYTHONPATH=./ python3 src/train.py \
  --int_rew_source=NovelD \
  --env_source=minigrid \
  --game_name=DoorKey-8x8 \
  --int_rew_coef=3e-2 \
  --rnd_err_norm=0

the error messages are as follow:
Traceback (most recent call last):
  File "/home/server/PycharmProjects/deir-main/src/train.py", line 257, in <module>
    main()
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/server/PycharmProjects/deir-main/src/train.py", line 251, in main
    train(config)
  File "/home/server/PycharmProjects/deir-main/src/train.py", line 119, in train
    model.learn(
  File "/home/server/PycharmProjects/deir-main/src/algo/ppo_trainer.py", line 322, in learn
    return super(PPOTrainer, self).learn(
  File "/home/server/PycharmProjects/deir-main/src/algo/ppo_rollout.py", line 744, in learn
    continue_training = self.collect_rollouts(
  File "/home/server/PycharmProjects/deir-main/src/algo/ppo_rollout.py", line 673, in collect_rollouts
    self.create_intrinsic_rewards(new_obs, actions, dones)
  File "/home/server/PycharmProjects/deir-main/src/algo/ppo_rollout.py", line 608, in create_intrinsic_rewards
    return self.policy.int_rew_model.get_intrinsic_rewards(
  File "/home/server/PycharmProjects/deir-main/src/algo/intrinsic_rewards/noveld.py", line 102, in get_intrinsic_rewards
    self.forward(curr_obs, next_obs, last_mems, curr_dones)
  File "/home/server/PycharmProjects/deir-main/src/algo/intrinsic_rewards/noveld.py", line 85, in forward
    curr_tgt, curr_prd, next_tgt, next_prd = self.model_mlp(curr_embs, next_embs)
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/server/PycharmProjects/deir-main/src/algo/common_models/mlps.py", line 236, in forward
    curr_tgt, curr_prd = self.noveld_rnd_model(curr_emb)
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/server/PycharmProjects/deir-main/src/algo/common_models/mlps.py", line 183, in forward
    target_outputs = self.target(emb)
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/server/anaconda3/envs/deir/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x64 and 128x256)

Is the code incompatible with other algorithms？

**Comment by swan-utokyo** [comment]
@dooliu Thank you for your question. Based on the error message you provided, "RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x64 and 128x256)", it indicates that the dimensions of your input embeddings might not match the definitions of the neural network model. It is therefore recommended to check the embedding dimensions you are using, the number of hidden units in your model, and whether the versions of related libraries you installed are all compatible. 

Please kindly note that the code provided in this repository (including DEIR and NovelD) has only been tested to be compatible with the gym and MiniGrid versions used in our experiments (gym==0.23.1, gym-minigrid==1.0.3, and more detailed in [requirement.txt](https://github.com/swan-utokyo/deir/blob/main/requirements.txt)). We have not tested its compatibility with other versions of libaries and environments.

For more information about how to train DEIR and NovelD with our implementations, you can also refer to an earlier discussion (see issue https://github.com/swan-utokyo/deir/issues/2).

**Comment by dooliu** [comment]
Thank you very much. I solved the problem.

The value setting of the model_features_dim parameter in the NovelDModel file needs to be changed from 256 to 64.
